language: c

compiler: gcc

python:
  - "3.5"

before_install:
  - sudo apt-get update
  - sudo apt-get install python3

install:
  - pip install --user --upgrade pip
  - make deps-travis

script: make test
