language: c

compiler: gcc

python:
  - "3.5"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3-setuptools python3-venv

install:
  - python3 -m venv .
  - source ./bin/activate
  - pip install --upgrade pip
  - pip install -r requirements.txt

script: make test
