sudo: required
dist: trusty
language: c

compiler: gcc

python:
  - "3.5"

install:
  - sudo apt-get update
  - sudo apt-get -y install python3-setuptools python-virtualenv
  - virtualenv --python=$(which python3) .venv
  - source .venv/bin/activate
  - pip install --upgrade pip
  - pip install -r requirements.txt

script: make test
